---
summary: Build the `runlog` server.

description: |
  The `build-server` task builds the `runlog` server from the
  main package defined in `./cmd/server/`, leaving the binary
  in the current working directory as `runlogd`.

  This task runs in a Linux container. If working on Mac OS
  make sure to set GOOS appropriately.

image: golang:1.11-stretch

mount: /go/src/github.com/run-ci/runlog

command: go build -v -o runlogd ./cmd/server/

arguments:
  GOOS:
    description: Platform to build for.
    default: linux
